[project]
name = "pydantic-config"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Sami Jaghouar", email = "sami.jaghouar@gmail.com" }
]
dependencies = ["pydantic>=2.0.0"]
readme = "README.md"
requires-python = ">= 3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = ["pytest>=7.0.0", "pre-commit>=3.0.0"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/pydantic_cli"]

[tool.hatch.version]
path = "src/pydantic_cli/__init__.py"
